import {
  // ExclamationTriangleIcon as ErrorIconMini,
  CheckCircleIcon as CheckCircleIconMini,
  EyeIcon as EyeIconMini,
  EyeSlashIcon as EyeSlashIconMini,
  InformationCircleIcon as InformationCircleIconMini,
  NoSymbolIcon as Blocking,
  CheckCircleIcon as CheckIconMini,
  ChevronDownIcon as ChevronDownIconMini,
  AdjustmentsHorizontalIcon as ViewIcon,
  GlobeAltIcon as GlobalIcon,
  MagnifyingGlassIcon as MagnifyingGlassIconOutline,
  
} from "@heroicons/react/20/solid";
import {
  // UserIcon as UserIcon,
  EyeSlashIcon,
  EyeIcon,
  PhotoIcon as ImageIcon,
  CheckIcon as CheckIconOutline,
  Bars3CenterLeftIcon as SidebarIcon,
  ExclamationTriangleIcon as ExclamationTriangleIconOutline,
  CloudArrowUpIcon as CloudIcon,
  CheckCircleIcon as CircleCheck,
  ChevronDownIcon as ChevronDownIcon,
  MagnifyingGlassPlusIcon as Magnification,
  ChevronRightIcon as  ChevronRightIcon ,
  ChevronLeftIcon as  ChevronLeftIcon ,
} from "@heroicons/react/24/outline";

export {
  CheckIconOutline,
  EyeIcon,
  EyeIconMini,
  EyeSlashIconMini,
  EyeSlashIcon,
  ChevronDownIconMini,
  CheckIconMini,
  Blocking,
  ImageIcon,
  ViewIcon,
  CheckCircleIconMini,
  ExclamationTriangleIconOutline,
  InformationCircleIconMini,
  GlobalIcon,
  MagnifyingGlassIconOutline,
  CloudIcon,
  CircleCheck,
  SidebarIcon,
  ChevronDownIcon,
  Magnification,
  ChevronRightIcon,
  ChevronLeftIcon
};
