import USD from './USD.svg';
import AED from './AED.svg';
import Instagram from './instagram.svg'
import Facebook from './face.svg'
import whatsapp from './whatsapp.svg'
import hero from './hero.svg'
import leftArrow from './leftArrow.svg'
import pepole from './people.svg'
import location from './location.svg'
import star from './star.svg'
import  test from './test.svg' 
import leftSlide from './leftSlide.svg'
import rightSlide from './rightSlide.svg'
import arrowUpR from './arrowUpR.svg'
import rightArrow from './rightArrow.svg'
import arrowBlue from './arrowBlue.svg'
import Hero2 from './Hero2.svg'
import hero3 from './hero3.svg'
import test2 from './test2.svg'
import bestDeal from './bestDeals.svg'
import arrowDown from './arrowDown.svg'
import Guest from './Guest.svg'
import dataTime from './dataTime.svg'
import activity from './activity.svg'
import sort from './sort.svg'
import toggleMenu from './toggleMenu.svg'
import timer from './timer.svg'
import convert from './convert.svg'
import seats from './seats.svg'
import test3 from './test3.svg'
import stars from './stars.svg'


export {test2,toggleMenu,sort,activity,dataTime,arrowDown,Guest ,bestDeal,rightArrow,hero3 ,arrowBlue ,Hero2,USD,arrowUpR,seats ,test3,convert,stars,timer,AED,whatsapp,Facebook,Instagram , hero ,leftArrow ,pepole , location , star ,test ,rightSlide ,leftSlide}